language: python
python: 3.7

cache:
  directories:
  - $HOME/.cache/pre-commit

install:
- ci/install.sh

script:
- pre-commit run --all-files
- pre-commit run --all-files --hook-stage manual
- ci/build.sh

deploy:
  provider: script
  skip_cleanup: true
  script: ci/deploy.sh

  on:  # yamllint disable-line rule:truthy
    branch: master
