language: python
python: 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

install:
  - "pip install -U pip"
  - "pip install Lektor"

script:
  - "cd example-site"
  - "lektor build -v"

deploy:
  provider: script
  script: "lektor deploy ghpages"
  on:
    branch: master
